on:
    push:
        branches:
            - main
    pull_request:

name: CI

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer

        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - 7.2

                dependencies:
                    - highest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2.4.0

            -
                name: Install PHP with extensions
                uses: shivammathur/setup-php@2.17.1
                with:
                    coverage: none
                    php-version: ${{ matrix.php-version }}

            -
                name: "Install dependencies with composer"
                uses: "ramsey/composer-install@2.1.0"
                with:
                    composer-options: "--no-scripts"

            -
                name: "Run friendsofphp/php-cs-fixer"
                run: "vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --verbose"

    composer-normalize:
        name: composer-normalize

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.4.0

            - name: composer-normalize
              uses: docker://ergebnis/composer-normalize-action:0.8.0

    phpstan:
        name: PHPStan

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.4.0

            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga:0.12.86
              with:
                  args: analyse src --level=7

    tests:
        name: "PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }}"

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allowed-to-fail }}

        strategy:
            matrix:
                php-version:
                    - '7.2'
                    - '7.3'
                    - '7.4'
                    - '8.0'
                dependencies:
                    - 'lowest'
                    - 'highest'
                allowed-to-fail: [false]

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2.4.0

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@2.17.1
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"
                  tools: "composer:v2"

            - name: Add PHPUnit matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Composer install"
              uses: "ramsey/composer-install@2.1.0"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
                  composer-options: "--prefer-dist"

            - name: Run tests
              run: vendor/bin/phpunit -v
